# Generated by Django 6.0.6 on 2026-06-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
