# Generated by Django 6.0.6 on 2026-06-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_spending_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD')], default='CAD', max_length=3),
        ),
    ]
